version: '3.1'

# Services
services:
  # PostgreSQL
  postgres:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}

  # Redis
  redis:
    image: redis
    volumes:
      - redis:/data

  # Nginx
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django/{{cookiecutter.repo_name}}/media:/media:ro
      - ./django/{{cookiecutter.repo_name}}/static:/static:ro
    environment:
      VIRTUAL_HOST: {{cookiecutter.virtual_host}}

  # pgweb
  pgweb:
    image: donnex/pgweb
    environment:
      VIRTUAL_HOST: pgweb.{{cookiecutter.virtual_host}}

  # Assets
  assets:
    image: donnex/assets
    ports:
      - "35729:35729"
    volumes:
      - ./assets/gulpfile.js:/gulp/gulpfile.js:ro
      - ./django/{{cookiecutter.repo_name}}/sass:/gulp/sass
      - ./django/{{cookiecutter.repo_name}}/static/css:/gulp/css
      - ./django/{{cookiecutter.repo_name}}/static/js:/gulp/js

  # Django python
  django:
    build:
      context: ./django
      args:
        requirements_file: requirements/dev.txt
    volumes:
      - ./django/{{cookiecutter.repo_name}}:/wwwroot
    environment:
      - DJANGO_CONFIGURATION=Dev
      - DJANGO_SECRET_KEY={{cookiecutter.django_secret_key}}
      - DJANGO_HIREDIS_CACHE_LOCATION=redis:6379
      - DJANGO_ALLOWED_HOSTS={{cookiecutter.virtual_host}}
      - DATABASE_URL=postgres://postgres:{{cookiecutter.postgres_password}}@postgres/{{cookiecutter.repo_name}}?sslmode=disable
      - EMAIL_URL=console://
    command: gunicorn --log-level info --log-file=- --workers 4 --name {{cookiecutter.repo_name}}_gunicorn -b 0.0.0.0:8000 --reload {{cookiecutter.repo_name}}.wsgi:application


# Volumes
volumes:
  postgres:
  redis:
